Well... stuff builds
since app_process requires so much of the system to be initialized and used, I decided to implement my own webos_runtime, and base it off of the android_runtime library.

I'm currently stuck on a stupid linker error:
../frameworks/base/libs/utils/libutils.so: undefined reference to `_Unwind_Backtrace@GCC_4.3.0'

It's particularly frustrating because I can't duplicate the issue with a simple test. Commenting out the call to _Unwind_Backtrace does allow CallStack.cpp to compile, but I didn't get an execution test after that.

Ideally, with a gutted libwebos_runtime.so, app_process should be able to start, and at least attempt to load an apk, and then fail due to non-initialized JNI runtimes, like OpenGL, ect. I'm hoping it will allow us to implement bare-minimum functionality to get simple "Hello World" apps loaded, and move on from there, rather than trying to get everything done all at the same time.