Fixed compile problem with ASM files
Configured CMake to use the ASM-ATT dialect for .S files, so they now
compile. Missing symbols down to:
Linking CXX executable dalvikvm
../../system/core/libcutils/libcutils.so: undefined reference to `selectorCreate'
../vm/libdvm.so: undefined reference to `dvm_dalvik_system_Zygote'
../vm/libdvm.so: undefined reference to `dlmalloc_trim'
../vm/libdvm.so: undefined reference to `dlmalloc_inspect_all'
../../system/core/libcutils/libcutils.so: undefined reference to `selectorLoop'
../../system/core/libcutils/libcutils.so: undefined reference to `selectorAdd'
../../system/core/libcutils/libcutils.so: undefined reference to `__reboot'
../../system/core/libcutils/libcutils.so: undefined reference to `selectorWakeUp'