Fixed missing symbols in cutils
Missing symbols for dalvikvm are now down to:
../vm/libdvm.so: undefined reference to `dvm_dalvik_system_Zygote'
../../system/core/libcutils/libcutils.so: undefined reference to `__reboot'

Zygote won't compile:
dalvik/vm/native/dalvik_system_Zygote.cpp:23:29: error: selinux/android.h: No such file or directory
dalvik/vm/native/dalvik_system_Zygote.cpp: In function ‘pid_t forkAndSpecializeCommon(const u4*, bool)’:
dalvik/vm/native/dalvik_system_Zygote.cpp:652: error: ‘ADDR_NO_RANDOMIZE’ was not declared in this scope

So we are missing that symbol.

I think __reboot is a macro, hopefully simple to port.